db:
  image: mysql:5.7
  ports:
    - "3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=chat
    - MYSQL_PASSWORD=PaSSw0rd
    - MYSQL_DATABASE=chat
  volumes:
    - ./db:/docker-entrypoint-initdb.d:ro
  command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
  hostname: db

app:
  image: node:alpine
  ports:
    - "80:80"
  environment: 
    - PORT=80
  volumes:
    - .:/app
  working_dir: /app
  links:
    - db
  command: npm install && npm install -g forever && forever start index.js 
  hostname: app
